data:
  num_workers: 4
  output: x-umx_outputs
  sample_rate: 44100
  samples_per_track: 64
  seed: 42
  seq_dur: 6.0
  source_augmentations:
  - gain
  - channelswap
  sources:
  - bass
  - drums
  - vocals
  - other
  train_dir: E:\unzip_multitrack
main_args:
  help: null
model:
  bandwidth: 16000
  bidirectional: true
  hidden_size: 512
  in_chan: 4096
  nb_channels: 2
  nhop: 1024
  pretrained: null
  spec_power: 1
  window_length: 4096
optim:
  lr: 0.001
  lr_decay_gamma: 0.3
  lr_decay_patience: 80
  optimizer: adam
  patience: 1000
  weight_decay: 1.0e-05
positional arguments: {}
training:
  batch_size: 14
  epochs: 1000
  loss_combine_sources: true
  loss_use_multidomain: true
  mix_coef: 10.0
  val_dur: 80.0
